global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'cucristi@gmail.com'
  smtp_auth_username: 'cucristi@gmail.com'
  smtp_auth_password: 'ndpf wkaa bjoe eirf' #using app password
  smtp_require_tls: true

  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  group_by: ['alertname', 'severity']
  receiver: mail

  routes:
    - matchers:
        - severity=~critical|warning
      receiver: mail
      continue: true
    - matchers:
        - severity=~critical|warning
      receiver: slack

receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
        # https://api.slack.com/messaging/webhooks
        api_url: 'https://hooks.slack.com/services/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D'
        channel: '#alerts'
        title: '{{ .CommonLabels.alertname }}'
        icon_emoji: '{{ if eq .Status "firing" }} :fire: {{ else }} :white_check_mark: {{end}} '
        text: >-
          {{ range .Alerts }}
          {{ if eq .Status "firing" }} :fire: {{else}} :white_check_mark: [RESOLVED] {{end}}*Alert:* {{ .Annotations.summary }}
            *Status:* {{ .Status }}
            *Instance:* {{ .Labels.instance }}
            *Severity:* {{ .Labels.severity }}
            *Description:* {{ .Annotations.description }}
            {{ if eq .Status "firing" -}}
            :clock1: *Time:* {{ .StartsAt | date "2006-01-02 15:04:05 UTC" }}
            {{- else -}}
            :clock1: *Time:* {{ .EndsAt | date "2006-01-02 15:04:05 UTC" }}
            {{- end}}
          {{ end }}

  - name: mail
    email_configs:
      - to: 'example@gmail.com'
        from: 'example@gmail.com'
        send_resolved: true

templates:
    - /etc/alertmanager/templates/*.tmpl
