{
 "title": "Windows Update Monitoring",
 "description": "Monitoring of Windows updates and pending reboots with Prometheus",
 "tags": [
  "Prometheus",
  "Windows"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_os_hostname,instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Systems Require Reboot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(win_update_reboot_required)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security Upgrades Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(win_upgrades_pending{category=\"security\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upgrades Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "win_upgrades_pending{instance=~\"$instance\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Security Upgrades Pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "win_upgrades_pending{category=~\"security\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upgrades Pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "win_upgrades_pending{category!~\"security\", instance=~\"$instance\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Windows Update Check",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(instance)(win_update_reboot_required)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance)(win_upgrades_pending{category=\"security\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(instance)(win_upgrades_pending{category!~\"security\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}