#
#   Usage:
#   ansible-playbook -i inventory/dev/hosts.ini playbooks/dev.yml -e "config=update"
#
###############################################################################
- name: Gathering valid config params
  set_fact:
    params: [update, check, reboot]


###############################################################################
- name: Attempt to trigger task
  block:
    - name: Running "{{ config }}" task
      include_tasks: "{{ config }}.yml"

  rescue:
    - name: Report failed task
      fail:
        msg: |
          {% if config not in params %}
          Invalid config "{{ config | default("undefined") }}". Expected: {{ params }}

          {% else %}
          Task "{{ config }}" failed during execution.

          {% endif %}